# Generated by Django 3.1.7 on 2021-04-04 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('native_language', models.CharField(max_length=100)),
                ('hobbies', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Eng', 'English'), ('Mandarin', 'Mandarin'), ('Spanish', 'Spanish')], max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('birthdate', models.DateTimeField()),
                ('street', models.CharField(max_length=100)),
                ('zipcode', models.IntegerField()),
                ('country', models.CharField(default='USA', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Visio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visio_start', models.DateTimeField()),
                ('visio_end', models.DateTimeField()),
                ('visio_date', models.DateTimeField()),
                ('validation_status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed')], max_length=10)),
                ('child_correspondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_correspondent', to='main.child')),
                ('child_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_participant', to='main.child')),
                ('correspondent_language', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='correspondent_language', to='main.language')),
                ('participant_language', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='participant_language', to='main.language')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_date', models.DateTimeField(verbose_name='date sent')),
                ('content', models.TextField()),
                ('message_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_from', to='main.parent')),
                ('message_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_to', to='main.parent')),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='language_to_learn',
            field=models.ManyToManyField(default='English', to='main.Language'),
        ),
    ]
