# Generated by Django 3.1.7 on 2021-04-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='language_to_learn',
        ),
        migrations.AddField(
            model_name='child',
            name='languagetolearn',
            field=models.ManyToManyField(blank=True, to='main.Language'),
        ),
    ]
